### ISSUE TITLE
Steps Tracker bugs and needed improvement.

### ISSUE THREAD

**Issue by Bonzzz3** [Bonzzz3/darth_runner#3]
- Location accuracy causes the user to move even when not moving.
- Polyline cannot be discontinuous or cant change colour midway.
- Distance resets to zero so need to create a separate list that will refresh on pause.
- Pace calculation is not accurate

**Comment by Cjoshd** [comment]
:( i skilll issue sorry

**Comment by domlimm** [comment]
eh yall only created 1 issue!!

**Comment by Bonzzz3** [comment]
> eh yall only created 1 issue!!


I have created another issue, we usually communicate directly through chat. But we will create more issues in the future. 😅

**Comment by domlimm** [comment]
no worries kelly. it's okay lah i was just checking haha. good job both of you, for ms2! 🏆

**Comment by Cjoshd** [comment]
pace calculation fixed
